import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header';
import { Outfit } from 'next/font/google';
const outfit = Outfit({ subsets: ['latin'], weight: ['100', '400', '700', '900'] });

export const metadata: Metadata = {
  title: "Tsirang Hospital",
  description: "Generated by create next app",
  icons: {
    icon: '/image2.jpg', // Path to your favicon (ensure it's in the `public` folder)
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Correct way to set the favicon */}
        <link rel="icon" href="/image2.jpg" type="image/jpeg" />
      </head>

      <body className={outfit.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
