import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header'
import { Outfit } from 'next/font/google';
const outfit = Outfit({ subsets: ['latin'], weight: ['100', '400', '700', '900'] });


export const metadata: Metadata = {
  title: "Tsirang Hospital | Geylegphug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        

      <body
        className={outfit.className}
      >
         <Header/>
        {children}
      </body>
    </html>
  );
}
