/*import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header';
import { Outfit } from 'next/font/google';
const outfit = Outfit({ subsets: ['latin'], weight: ['100', '400', '700', '900'] });

export const metadata: Metadata = {
  title: "Tsirang Hospital",
  description: "Generated by create next app",
  icons: {
    icon: '/image2.jpg', // Path to your favicon (ensure it's in the `public` folder)
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>*/
        {/* Correct way to set the favicon */}
        /*
        <link rel="icon" href="/image2.jpg" type="image/jpeg" />
      </head>

      <body className={outfit.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}*/
import type { Metadata } from "next";
import { AuthProvider } from './Providers'; // Ensure this is set up properly
import { SelectedItemsProvider } from './context/SelectedItemsContext';
import { Outfit } from 'next/font/google';


import "./globals.css";

// Use the correct property for weight
const outfit = Outfit({ subsets: ['latin'], weight: ['100', '400', '700', '900'] });

export const metadata: Metadata = {
  title: "Tsirang Hospital",
  description: "Generated by create next app",
  icons: {
    icon: '/image2.jpg', 
  },
};

// Define the type for the props
interface RootLayoutProps {
  children: React.ReactNode; // Use ReactNode for children
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className={outfit.className}> 
        <SelectedItemsProvider>
          <AuthProvider>
            {children}
            {/* <Footer />  Include Footer for consistency */}
          </AuthProvider>
        </SelectedItemsProvider>
      </body>
    </html>
  );
}

