// app/metadata.ts
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tsirang Hospital",
  description: "Generated by create next app",
  icons: {
    icon: '/image2.jpg', // Path to your favicon (ensure it's in the `public` folder)
  },
};